use std::io::{self,Stdout};
use std::sync::Arc;
use std::time::Duration;
use crossterm::{event::{self,Event,KeyCode,KeyEventKind,KeyModifiers,KeyboardEnhancementFlags,PopKeyboardEnhancementFlags,PushKeyboardEnhancementFlags},execute,terminal::{disable_raw_mode,enable_raw_mode,EnterAlternateScreen,LeaveAlternateScreen}};
use lucy_core::AgentEvent;
use lucy_runtime::LucyRuntime;
use lucy_stt::GroqStt;
use ratatui::{backend::CrosstermBackend,layout::{Constraint,Direction,Layout},style::{Modifier,Style},text::{Line,Span},widgets::{Block,Borders,List,ListItem,Paragraph,Wrap},Terminal};
use tokio::sync::mpsc;
const VOICE_HOTKEY:&str="Super+C / Ctrl+Space / F2";
pub struct App{pub status:String,pub listening:bool,pub commands:Vec<String>,pub input:String}
impl Default for App{fn default()->Self{Self{status:"Ready — type below or press Super+C / Ctrl+Space / F2 to speak".into(),listening:false,commands:Vec::new(),input:String::new()}}}
fn draw(terminal:&mut Terminal<CrosstermBackend<Stdout>>,app:&App)->anyhow::Result<()>{terminal.draw(|frame|{let outer=Layout::default().direction(Direction::Vertical).constraints([Constraint::Min(5),Constraint::Length(3),Constraint::Length(3),Constraint::Length(1)]).split(frame.area());let history=if app.commands.is_empty(){vec![ListItem::new(Line::from(Span::styled("No commands yet.",Style::default().add_modifier(Modifier::DIM)))),ListItem::new(Line::from(Span::styled("• Type a prompt and press Enter",Style::default().add_modifier(Modifier::DIM)))),ListItem::new(Line::from(Span::styled("• Or press Super+C / Ctrl+Space / F2 to speak",Style::default().add_modifier(Modifier::DIM))))]}else{app.commands.iter().map(|c|ListItem::new(Line::from(c.as_str()))).collect()};frame.render_widget(List::new(history).block(Block::default().title(" Command History ").borders(Borders::ALL)),outer[0]);let status=if app.listening{"🎙  Listening… speak now, then pause"}else{&app.status};frame.render_widget(Paragraph::new(status).block(Block::default().title(" Status ").borders(Borders::ALL)).wrap(Wrap{trim:true}),outer[1]);frame.render_widget(Paragraph::new(format!("> {}",app.input)).block(Block::default().title(" Input — type + Enter to send ").borders(Borders::ALL)),outer[2]);frame.set_cursor_position((outer[2].x+2+app.input.len()as u16,outer[2].y+1));frame.render_widget(Paragraph::new(format!("[{}] voice   [Enter] send   [Esc] quit",VOICE_HOTKEY)).style(Style::default().add_modifier(Modifier::DIM)),outer[3]);})?;Ok(())}
fn cleanup(terminal:&mut Terminal<CrosstermBackend<Stdout>>)->anyhow::Result<()>{disable_raw_mode()?;execute!(terminal.backend_mut(),PopKeyboardEnhancementFlags,LeaveAlternateScreen)?;terminal.show_cursor()?;Ok(())}
pub async fn run_voice(stt:Option<Arc<GroqStt>>)->anyhow::Result<()>{
 let runtime=Arc::new(LucyRuntime::new().await?);enable_raw_mode()?;let mut stdout=io::stdout();execute!(stdout,EnterAlternateScreen,PushKeyboardEnhancementFlags(KeyboardEnhancementFlags::DISAMBIGUATE_ESCAPE_CODES))?;let backend=CrosstermBackend::new(stdout);let mut terminal=Terminal::new(backend)?;let mut app=App::default();if stt.is_none(){app.status="STT unavailable — set GROQ_API_KEY to enable voice".into();}
 let(voice_tx,mut voice_rx)=mpsc::unbounded_channel::<Result<String,String>>();let mut voice_task_running=false;let mut agent_rx:Option<mpsc::UnboundedReceiver<AgentEvent>>=None;
 let result=loop{draw(&mut terminal,&app)?;
  let mut agent_done=false;
  if let Some(rx)=agent_rx.as_mut(){loop{match rx.try_recv(){Ok(event)=>match event{AgentEvent::Status{message}=>app.status=message,AgentEvent::TextDelta{text}=>{app.commands.push(format!("Lucy › {text}"));app.status="Working…".into();},AgentEvent::ToolStarted{name,..}=>app.status=format!("Using {name}…"),AgentEvent::ToolFinished{..}|AgentEvent::History{..}|AgentEvent::Thinking{..}=>{},AgentEvent::Error{message}=>app.status=format!("Error: {message}"),AgentEvent::Done=>{agent_done=true;break}},Err(mpsc::error::TryRecvError::Empty)=>break,Err(mpsc::error::TryRecvError::Disconnected)=>{agent_done=true;break}}}}
  if agent_done{agent_rx=None;app.status="Ready".into();}
  while let Ok(result)=voice_rx.try_recv(){voice_task_running=false;app.listening=false;match result{Ok(text)if !text.trim().is_empty()=>{let text=text.trim().to_owned();app.commands.push(format!("You › {text}"));app.status="Executing…".into();agent_rx=Some(runtime.submit(text).await?);},Ok(_)=>app.status="I didn't catch anything — try again".into(),Err(e)=>app.status=format!("Voice error: {e}")}}
  if event::poll(Duration::from_millis(50))?{if let Event::Key(key)=event::read()?{if key.kind!=KeyEventKind::Press{continue}let hotkey=(key.code==KeyCode::Char('c')&&key.modifiers.contains(KeyModifiers::SUPER))||(key.code==KeyCode::Char(' ')&&key.modifiers.contains(KeyModifiers::CONTROL))||key.code==KeyCode::F(2)||key.code==KeyCode::F(9)||(key.code==KeyCode::Char('v')&&key.modifiers.contains(KeyModifiers::ALT))||(key.code==KeyCode::Char('m')&&key.modifiers.contains(KeyModifiers::CONTROL));if hotkey&&!voice_task_running{if let Some(stt)=stt.as_ref(){let stt=Arc::clone(stt);let tx=voice_tx.clone();voice_task_running=true;app.listening=true;app.status="Listening…".into();tokio::spawn(async move{let _=tx.send(stt.listen_once().await.map_err(|e|e.to_string()));});}else{app.status="Voice disabled — set GROQ_API_KEY".into()}continue}match key.code{KeyCode::Esc=>break Ok(()),KeyCode::Char(c)if !key.modifiers.intersects(KeyModifiers::CONTROL|KeyModifiers::ALT|KeyModifiers::SUPER)=>app.input.push(c),KeyCode::Backspace=>{app.input.pop();},KeyCode::Enter if !app.input.trim().is_empty()=>{let text=app.input.trim().to_owned();app.input.clear();app.commands.push(format!("You › {text}"));app.status="Executing…".into();agent_rx=Some(runtime.submit(text).await?);},_=>{}}}}}}
 let cleanup_result=cleanup(&mut terminal);result.and(cleanup_result)
}
pub async fn run()->anyhow::Result<()>{let stt=GroqStt::from_env().ok().map(Arc::new);run_voice(stt).await}
