//! Lucy runtime: combines the latency-sensitive Lucy execution engine with
//! optional ADK-Rust extension services.
mod execution;
mod planner;
mod prompts;
mod sessions;
pub use execution::{build_waves, has_dependency_cycle, parallel_candidate, ExecutionWave};
pub use planner::SubTask;
pub use sessions::trim_history;
use std::{collections::{HashMap, HashSet, VecDeque}, path::PathBuf, sync::Arc};
use anyhow::{anyhow, Result};
use lucy_adk::{AdkCapability, LucyAdk};
use lucy_agent::{Agent, OpenAIProvider};
use lucy_config::LucyConfig;
use lucy_core::{AgentEvent, ApprovalDecision, ApprovalGate, AssistantTurn, ExecutionMode, InterruptSignal, SessionData, SessionId, SessionStore, TokenUsage, ToolContext, ToolResult, TurnMessage};
use lucy_hyprfast::HyprFastCatalog;
use lucy_mcp::{load_config, register_server};
use lucy_tools::{default_registry, ToolRegistry};
use serde_json::Value;
use tokio::sync::{mpsc, Mutex};
use planner::{action_requires_verification, build_context, decide_next, plan_command, triage_request, truncate_json, validate_plan, validate_replanned_subtask, verification_subtask, DecisionKind};
use sessions::now;
const MAX_CONTEXT_CHARS: usize = 16_000;
const MAX_ACTIONS: usize = 64;
const MAX_MAIN_DECISIONS: usize = 12;
const MAX_REPLANS: usize = 8;

pub struct LucyRuntime { agent:Arc<Agent<OpenAIProvider>>, registry:Arc<ToolRegistry>, provider:Arc<OpenAIProvider>, session:Arc<Mutex<SessionData>>, store:SessionStore, #[allow(dead_code)] legacy_path:PathBuf, interrupt:InterruptSignal, working_dir:PathBuf, hyprfast:Option<HyprFastCatalog>, config:LucyConfig, approvals:ApprovalGate, adk:Arc<LucyAdk> }
impl LucyRuntime {
    pub async fn new()->Result<Self>{
        let config=LucyConfig::load()?;let provider=Arc::new(OpenAIProvider::from_config(&config)?);let mut registry=default_registry();
        let hf_cfg=lucy_mcp::McpServerConfig{name:"hyprfast".into(),command:config.hyprfast.command.clone(),args:config.hyprfast.args.clone(),env:Default::default()};
        let hyprfast=match HyprFastCatalog::discover(hf_cfg.clone()).await{Ok(c)=>{tracing::info!(tools=c.len(),"HyprFast MCP connected");let _=c.save().await;Some(c)},Err(e)=>{tracing::warn!(error=%e,"HyprFast MCP unavailable; continuing without desktop capabilities");None}};
        for server in load_config()?{if server.name.eq_ignore_ascii_case("hyprfast"){continue}if let Err(e)=register_server(&mut registry,server.clone()).await{tracing::warn!(server=%server.name,error=%e,"MCP server unavailable")}}
        if hyprfast.is_some(){if let Err(e)=register_server(&mut registry,hf_cfg).await{tracing::warn!(error=%e,"failed to register HyprFast MCP tools")}}
        let legacy_path=config.sessions.file.clone().or_else(||std::env::var("LUCY_SESSION_FILE").ok().map(PathBuf::from)).unwrap_or_else(||PathBuf::from(std::env::var("HOME").unwrap_or_else(|_|".".into())).join(".local/state/lucy/session.json"));
        let store_dir=config.sessions.dir.clone().or_else(||std::env::var("LUCY_SESSIONS_DIR").ok().map(PathBuf::from)).unwrap_or_else(SessionStore::default_dir);let adk=Arc::new(LucyAdk::open(&store_dir).await);let store=SessionStore::new(store_dir);let _=store.migrate_legacy_file(&legacy_path).await;
        let session=if config.sessions.resume{match store.list().await{Ok(list)if !list.is_empty()=>match store.load(&list[0].id).await{Ok(s)=>s,Err(_)=>store.create(None).await?},_=>store.create(None).await?}}else{store.create(None).await?};
        let registry=Arc::new(registry);let agent=Arc::new(Agent::new(provider.clone(),registry.clone()));let(approval_tx,_approval_rx)=mpsc::unbounded_channel();let approvals=ApprovalGate::new(approval_tx);if let Ok(mut m)=approvals.mode.write(){*m=config.approvals.mode.clone()}
        Ok(Self{agent,registry,provider,session:Arc::new(Mutex::new(session)),store,legacy_path,interrupt:InterruptSignal::new(),working_dir:std::env::current_dir()?,hyprfast,config,approvals,adk})
    }
    pub fn interrupt(&self){self.interrupt.fire()} pub fn hyprfast_catalog(&self)->Option<&HyprFastCatalog>{self.hyprfast.as_ref()} pub fn route_hyprfast(&self,prompt:&str)->Option<lucy_hyprfast::Route>{self.hyprfast.as_ref().map(|c|c.route(prompt))} pub fn config(&self)->&LucyConfig{&self.config} pub fn approval_state(&self)->ApprovalGate{self.approvals.clone()} pub fn resolve_approval(&self,call_id:&str,d:ApprovalDecision)->bool{self.approvals.resolve(call_id,d)} pub fn usage(&self)->TokenUsage{self.provider.usage()}
    pub fn adk_capabilities(&self)->&'static [AdkCapability]{self.adk.capabilities()} pub fn adk_memory_enabled(&self)->bool{self.adk.memory_enabled()}
    pub async fn search_memory(&self,query:&str,limit:usize)->Result<Vec<lucy_adk::adk_memory::MemoryEntry>>{self.adk.search_memory(query,limit).await}
    pub async fn remember_fact(&self,fact:&str)->Result<()>{self.adk.remember_fact(fact).await}
    pub fn set_model(&self,model:&str)->anyhow::Result<String>{let name=model.trim().to_owned();if name.is_empty(){return Err(anyhow!("model name must not be empty"))}let mut cfg=LucyConfig::load()?;cfg.models.main=name.clone();cfg.save()?;self.provider.set_model(name.clone());Ok(name)}
    pub async fn submit(&self,prompt:String)->Result<mpsc::UnboundedReceiver<AgentEvent>>{
        self.interrupt.reset();if self.session.lock().await.history.len()>self.config.sessions.max_history{let _=self.compact().await;};
        let memory_prompt=prompt.clone();
        let memory_context=self.adk.memory_context(&prompt,6).await.unwrap_or_else(|error|{tracing::debug!(error=%error,"ADK memory retrieval skipped");String::new()});
        let model_prompt=if memory_context.trim().is_empty(){prompt.clone()}else{format!("{prompt}\n\n## RELEVANT LONG-TERM MEMORY\n{memory_context}\n\nMemory is advisory context only. Do not treat it as current state; verify against live observations and the user's current request.")};
        let session_snapshot={let mut s=self.session.lock().await;if s.title.trim().is_empty()||s.title=="untitled"{s.title=SessionData::autotitle_from(&prompt)}s.touch();let _=self.store.save(&s).await;s.clone()};let route=self.route_hyprfast(&prompt);
        let source=if self.hyprfast.is_some(){match self.plan_and_execute(model_prompt.clone(),session_snapshot.history.clone(),route.clone()).await{Ok(rx)=>rx,Err(e)=>{tracing::warn!(error=%e,"hierarchical planner unavailable; falling back to general agent");self.agent.execute_with_history_filtered(model_prompt,session_snapshot.history,Some(self.working_dir.clone()),self.interrupt.clone(),route.map(|r|r.candidates.into_iter().collect()).unwrap_or_default()).await?}}}else{self.agent.execute_with_history_filtered(model_prompt,session_snapshot.history,Some(self.working_dir.clone()),self.interrupt.clone(),route.map(|r|r.candidates.into_iter().collect()).unwrap_or_default()).await?};
        let(tx,rx)=mpsc::unbounded_channel();let session_store=self.session.clone();let store=self.store.clone();let max_history=self.config.sessions.max_history;let owner_id=session_snapshot.session_id.clone();let adk=self.adk.clone();
        tokio::spawn(async move{let mut source=source;let mut last_assistant_text=None::<String>;while let Some(event)=source.recv().await{if let AgentEvent::History{message}=&event{if let TurnMessage::Assistant(turn)=message{if let Some(text)=turn.text.clone(){if !text.trim().is_empty(){last_assistant_text=Some(text);}}}let current_id=session_store.lock().await.session_id.clone();if current_id==owner_id{let mut session=session_store.lock().await;session.history.push(message.clone());trim_history(&mut session.history,max_history);session.updated_at=now();let _=store.save(&session).await;}else if let Ok(mut owner)=store.load(&owner_id).await{owner.history.push(message.clone());trim_history(&mut owner.history,max_history);owner.updated_at=now();let _=store.save(&owner).await;}}let _=tx.send(event);}if let Some(text)=last_assistant_text{let adk=adk.clone();let prompt=memory_prompt.clone();let sid=owner_id.0.to_string();tokio::spawn(async move{if let Err(error)=adk.remember_interaction(&sid,&prompt,&text).await{tracing::debug!(error=%error,"ADK memory write skipped");}});}});Ok(rx)
    }
    async fn plan_and_execute(&self,prompt:String,history:Vec<TurnMessage>,route:Option<lucy_hyprfast::Route>)->Result<mpsc::UnboundedReceiver<AgentEvent>>{
        let(tx,rx)=mpsc::unbounded_channel();let provider=self.provider.clone();let registry=self.registry.clone();let catalog=self.hyprfast.clone().ok_or_else(||anyhow!("HyprFast catalog unavailable"))?;let interrupt=self.interrupt.clone();let working_dir=self.working_dir.clone();let planner_cfg=self.config.planner.clone();let verify_actions=self.config.hyprfast.verify_actions;let main_model=self.provider.model();let command_model=self.config.models.hyprfast_command.clone();let approvals=self.approvals.clone();
        tokio::spawn(async move{let run=async{
            let _=tx.send(AgentEvent::History{message:TurnMessage::User(prompt.clone())});let _=tx.send(AgentEvent::Status{message:"Understanding your request…".into()});let _=tx.send(AgentEvent::Progress{message:"Understanding your request…".into()});let triage=triage_request(&provider,&main_model,&prompt,&catalog,&route,&history,&interrupt).await?;
            if triage.mode=="chat"{let text=triage.reply.filter(|r|!r.trim().is_empty()).unwrap_or_else(||"Done.".to_string());let assistant=TurnMessage::Assistant(AssistantTurn{text:Some(text.clone()),tool_calls:Vec::new()});let _=tx.send(AgentEvent::History{message:assistant});let _=tx.send(AgentEvent::TextDelta{text});return Ok::<(),anyhow::Error>(());}
            if triage.mode!="act"{return Err(anyhow!("main model returned unknown triage mode: {}",triage.mode));}if triage.subtasks.is_empty()||triage.subtasks.len()>planner_cfg.max_subtasks{return Err(anyhow!("main model returned an invalid subtask count"));}validate_plan(&triage.subtasks)?;
            let _=tx.send(AgentEvent::Progress{message:format!("Plan ready: {} step{}…",triage.subtasks.len(),if triage.subtasks.len()==1{""}else{"s"})});let mut queue:VecDeque<SubTask>=triage.subtasks.into_iter().collect();let mut completed:HashMap<String,Value>=HashMap::new();let mut notes=Vec::new();let mut seen_actions=HashSet::<String>::new();let mut seen_failures=HashSet::<String>::new();let mut decisions=0usize;let mut replans=0usize;let mut actions=0usize;let mut done_count=0usize;let mut deferred=0usize;
            while let Some(subtask)=queue.pop_front(){if interrupt.is_set(){return Err(lucy_core::LucyError::Cancelled.into());}if actions>=MAX_ACTIONS{return Err(anyhow!("computer-operation action budget exhausted; stopping to prevent a loop"));}if !subtask.depends_on.iter().all(|id|completed.contains_key(id)){queue.push_back(subtask);deferred+=1;if deferred>=queue.len().max(1){return Err(anyhow!("execution plan is blocked by unresolved dependencies"));}continue;}deferred=0;
                let step_no=done_count+1;let _=tx.send(AgentEvent::Status{message:format!("Step {step_no}: {}",subtask.goal)});let _=tx.send(AgentEvent::Progress{message:format!("Step {step_no}: {}",subtask.goal)});let cat=subtask.category.to_ascii_lowercase();
                let(allowed,context)=if cat=="files"||cat=="shell"||cat=="system"{let names=registry.local_tool_names();if names.is_empty(){return Err(anyhow!("no local tools available for subtask: {}",subtask.goal));}let mut ctx=String::from("Local machine tools. Prefer read-only observation tools when only inspecting; never invent file contents or command output.\n");for id in &subtask.depends_on{if let Some(v)=completed.get(id){ctx.push_str(&format!("\nDependency {id} result: {v}"));}}if ctx.len()>MAX_CONTEXT_CHARS{ctx.truncate(MAX_CONTEXT_CHARS);ctx.push_str("\n[context truncated]");}(names,ctx)}else{let subroute=catalog.route_domain(&subtask.category,&subtask.goal);let names:HashSet<String>=subroute.candidates.iter().cloned().collect();if names.is_empty(){return Err(anyhow!("no HyprFast tools matched subtask: {}",subtask.goal));}let ctx=build_context(&catalog,&subroute,&completed,&subtask.depends_on);(names,ctx)};
                let schemas=registry.definitions_for_names(&allowed);let command=plan_command(&provider,&command_model,&prompt,&subtask,&schemas,&context,&interrupt).await?;if !allowed.contains(&command.tool){return Err(anyhow!("command model selected tool outside routed capability set: {}",command.tool));}if !command.arguments.is_object(){return Err(anyhow!("command model arguments must be a JSON object"));}
                let action_key=format!("{}|{}|{}",subtask.goal.trim(),command.tool,command.arguments);if !seen_actions.insert(action_key){return Err(anyhow!("repeated identical action detected; stopping to prevent an execution loop"));}actions+=1;let call_id=format!("plan-{actions}");let gate=approvals.with_events(tx.clone());
                if gate.needs_approval(&command.tool,registry.requires_approval(&command.tool)){let _=tx.send(AgentEvent::Progress{message:format!("Needs your approval: {}…",command.tool)});match gate.ask(&call_id,&command.tool,&command.arguments).await{ApprovalDecision::AllowOnce|ApprovalDecision::AllowAlways=>{},ApprovalDecision::Deny=>{let denied=serde_json::json!({"denied by user":command.tool.clone()});let _=tx.send(AgentEvent::ToolFinished{id:call_id.clone(),name:command.tool.clone(),output:denied.clone(),is_error:true});if !planner_cfg.replan_on_failure{return Err(anyhow!("subtask denied: {}",subtask.goal));}if replans>=MAX_REPLANS{return Err(anyhow!("recovery budget exhausted after approval denial"));}replans+=1;let fingerprint=format!("deny|{}|{}",subtask.goal,command.tool);if !seen_failures.insert(fingerprint){return Err(anyhow!("repeated denied action detected; stopping recovery loop"));}completed.insert(format!("{}_failure",subtask.id),denied.clone());if decisions>=MAX_MAIN_DECISIONS{return Err(anyhow!("main-model recovery decision budget exhausted"));}decisions+=1;let decision=decide_next(&provider,&main_model,&prompt,&queue,&completed,&subtask,&denied,&catalog,&interrupt).await?;if let Some(s)=decision.subtask{validate_replanned_subtask(&s,&completed,&queue)?;queue.push_front(s);}continue;}}}
                let _=tx.send(AgentEvent::ToolStarted{id:call_id.clone(),name:command.tool.clone(),input:command.arguments.clone()});let ctx=ToolContext{session_id:SessionId::default(),tool_call_id:call_id.clone(),working_dir:Some(working_dir.clone()),execution_mode:ExecutionMode::Agent,events:tx.clone(),interrupt:interrupt.clone()};let result=registry.execute(&command.tool,command.arguments.clone(),ctx).await;
                let output=match result{Ok(v)=>{let _=tx.send(AgentEvent::ToolFinished{id:call_id.clone(),name:command.tool.clone(),output:v.clone(),is_error:false});v},Err(e)=>{let err=serde_json::json!({"error":e.to_string()});let _=tx.send(AgentEvent::ToolFinished{id:call_id.clone(),name:command.tool.clone(),output:err.clone(),is_error:true});if !planner_cfg.replan_on_failure{return Err(anyhow!("subtask failed: {}: {}",subtask.goal,e));}if replans>=MAX_REPLANS{return Err(anyhow!("recovery budget exhausted after repeated failures"));}let fingerprint=format!("failure|{}|{}|{}",subtask.goal,command.tool,e);if !seen_failures.insert(fingerprint){return Err(anyhow!("same action failed repeatedly; stopping instead of looping"));}replans+=1;let _=tx.send(AgentEvent::Progress{message:format!("Step failed ({e}) — replanning…")});completed.insert(format!("{}_failure",subtask.id),err.clone());if decisions>=MAX_MAIN_DECISIONS{return Err(anyhow!("main-model recovery decision budget exhausted"));}decisions+=1;let decision=decide_next(&provider,&main_model,&prompt,&queue,&completed,&subtask,&err,&catalog,&interrupt).await?;if let Some(s)=decision.subtask{validate_replanned_subtask(&s,&completed,&queue)?;queue.push_front(s);}continue;}};
                let state=truncate_json(output.clone());completed.insert(subtask.id.clone(),state.clone());notes.push(subtask.goal.clone());done_count+=1;let _=tx.send(AgentEvent::History{message:TurnMessage::Tool(ToolResult{call_id,name:command.tool.clone(),output:state.clone(),is_error:false})});let must_verify=verify_actions&&planner_cfg.verify_state&&action_requires_verification(&catalog,&command.tool,&subtask.category,command.verify.is_some())&&!subtask.id.starts_with("verify-");
                if must_verify{let _=tx.send(AgentEvent::Status{message:"Verifying the result…".into()});let _=tx.send(AgentEvent::Progress{message:"Verifying the result…".into()});queue.push_front(verification_subtask(&catalog,&command.tool,&subtask.goal,&subtask.category,decisions+1));continue;}
                if subtask.id.starts_with("verify-"){if decisions>=MAX_MAIN_DECISIONS{return Err(anyhow!("main-model verification decision budget exhausted"));}decisions+=1;let decision=decide_next(&provider,&main_model,&prompt,&queue,&completed,&subtask,&state,&catalog,&interrupt).await?;if let Some(s)=decision.subtask{validate_replanned_subtask(&s,&completed,&queue)?;queue.push_front(s);}else if matches!(decision.decision,DecisionKind::Replan){return Err(anyhow!("controller requested recovery without a valid recovery subtask"));}else if matches!(decision.decision,DecisionKind::Complete){let _=tx.send(AgentEvent::Status{message:format!("Done: {}",decision.reason)});let _=tx.send(AgentEvent::Progress{message:format!("Done: {}",decision.reason)});break;}}
            }
            let text=if notes.is_empty(){"Completed the request.".to_string()}else if notes.len()==1{format!("Completed: {}",notes[0])}else{let mut text=format!("Completed {} steps.",notes.len());for note in notes.iter().take(8){text.push_str(&format!("\n- {note}"));}text};let assistant=TurnMessage::Assistant(AssistantTurn{text:Some(text.clone()),tool_calls:Vec::new()});let _=tx.send(AgentEvent::History{message:assistant});let _=tx.send(AgentEvent::TextDelta{text});Ok::<(),anyhow::Error>(())
        };if let Err(e)=run.await{let _=tx.send(AgentEvent::Error{message:e.to_string()});};let _=tx.send(AgentEvent::Done);});Ok(rx)
    }
    pub async fn history(&self)->Vec<TurnMessage>{self.session.lock().await.history.clone()}
}