[package]
name = "lucy"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lucy"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
lucy-agent = { path = "../lucy-agent" }
lucy-acp = { path = "../lucy-acp" }
lucy-adk = { path = "../lucy-adk" }
lucy-core = { path = "../lucy-core" }
lucy-hyprfast = { path = "../lucy-hyprfast" }
lucy-tools = { path = "../lucy-tools" }
lucy-tui = { path = "../lucy-tui" }
lucy-stt = { path = "../lucy-stt" }
lucy-config = { path = "../lucy-config" }
lucy-runtime = { path = "../lucy-runtime" }
lucy-systemone = { path = "../lucy-systemone" }
lucy-mascot = { path = "../lucy-mascot" }
lucy-gateway = { path = "../lucy-gateway" }
reqwest.workspace = true
