[package]
name = "lucy"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lucy"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
lucy-agent = { path = "../lucy-agent" }
lucy-adk = { path = "../lucy-adk" }
lucy-core = { path = "../lucy-core" }
lucy-tools = { path = "../lucy-tools" }
lucy-tui = { path = "../lucy-tui" }
lucy-stt = { path = "../lucy-stt" }
lucy-config = { path = "../lucy-config" }
