use anyhow::{anyhow, Context, Result};
use lucy_core::*;
use reqwest::Client;
use serde_json::{json, Value};
use std::time::Duration;
use tokio::sync::mpsc;

#[derive(Debug,Clone)]
pub struct OpenAIProvider{client:Client,api_key:String,model:String,base_url:String}
impl OpenAIProvider{pub fn new(api_key:String,model:String,base_url:Option<String>)->Result<Self>{let client=Client::builder().timeout(Duration::from_secs(120)).build().context("failed to build HTTP client")?;Ok(Self{client,api_key,model,base_url:base_url.unwrap_or_else(||"https://api.openai.com/v1".into())})}pub fn from_env()->Result<Self>{Self::new(std::env::var("OPENAI_API_KEY").context("OPENAI_API_KEY is not set")?,std::env::var("OPENAI_MODEL").unwrap_or_else(|_|"gpt-4o".into()),std::env::var("OPENAI_BASE_URL").ok())}}
#[async_trait::async_trait]
impl ModelProvider for OpenAIProvider{async fn run_turn(&self,request:ModelRequest,_events:mpsc::UnboundedSender<AgentEvent>,interrupt:InterruptSignal)->Result<ModelTurn>{if interrupt.is_set(){return Err(LucyError::Cancelled.into());}let mut messages=vec![json!({"role":"system","content":"You are Lucy, an AI computer assistant. Use tools carefully and verify results."})];for msg in request.history{match msg{TurnMessage::User(t)=>messages.push(json!({"role":"user","content":t})),TurnMessage::Assistant{content,tool_calls}=>{let mut m=json!({"role":"assistant","content":content});if !tool_calls.is_empty(){m["tool_calls"]=json!(tool_calls.iter().map(|c|json!({"id":c.id,"type":"function","function":{"name":c.name,"arguments":c.input.to_string()}})).collect::<Vec<_>>());}messages.push(m)},TurnMessage::Tool(r)=>messages.push(json!({"role":"tool","tool_call_id":r.call_id,"name":r.name,"content":r.output.to_string()}))}}let mut payload=json!({"model":self.model,"messages":messages,"temperature":0.1});if !request.tools.is_empty(){payload["tools"]=json!(request.tools.iter().map(|t|json!({"type":"function","function":t})).collect::<Vec<_>>());}let url=format!("{}/chat/completions",self.base_url.trim_end_matches('/'));let res=self.client.post(url).bearer_auth(&self.api_key).json(&payload).send().await.context("OpenAI API request failed")?;let status=res.status();let body=res.text().await?;if !status.is_success(){return Err(anyhow!("OpenAI API returned {}: {}",status,body));}let v:Value=serde_json::from_str(&body).context("invalid JSON response from OpenAI")?;let message=&v["choices"][0]["message"];let text=message["content"].as_str().map(str::to_owned);let mut calls=Vec::new();if let Some(a)=message["tool_calls"].as_array(){for c in a{let id=c["id"].as_str().unwrap_or_default().to_owned();let name=c["function"]["name"].as_str().unwrap_or_default().to_owned();let args=c["function"]["arguments"].as_str().unwrap_or("{}");let input:Value=serde_json::from_str(args).context("model returned invalid tool arguments")?;calls.push(ToolCall{id,name,input});}}Ok(ModelTurn{text,tool_calls:calls.clone(),stop:calls.is_empty()})}}
