[package]
name = "lucy-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
lucy-agent = { path = "../lucy-agent" }
lucy-core = { path = "../lucy-core" }
lucy-hyprfast = { path = "../lucy-hyprfast" }
lucy-mcp = { path = "../lucy-mcp" }
lucy-tools = { path = "../lucy-tools" }
lucy-config = { path = "../lucy-config" }
